# Site settings
title: Daniel van den Brink
email: mail@danielvandenbrink.com
description: Hi. I'm Daniel. Please keep in mind that both this website and many of my projects are a work in progress.
baseurl: ""
url: "https://danielvandenbrink.com"
permalink: "/:categories/:title"
bitbucket_username: dvdbrink
github_username: dvdbrink

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.js"
